name: Terraform PR Check

on:
  pull_request:
    branches:
      - dev
      - stg
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Plan Check
    runs-on: ubuntu-latest

    env:
      REGION: ${{ secrets.REGION }}
    defaults:
        run:
            shell: bash
            working-directory:  terraform/environment/"${{ github.base_ref }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Set Environment Variables Based on Branch
        id: set_env
        run: |
          if [[ "${{ github.base_ref }}" == "dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.DEV_PROJECT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.base_ref }}" == "stg" ]]; then
            echo "ENVIRONMENT=stg" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.STG_PROJECT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.PRD_PROJECT_ID }}" >> $GITHUB_ENV
          fi

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="region=${{ secrets.REGION }}" -var="project_id=${{ env.PROJECT_ID }}" -input=false -target=module.sensors_artifact
